language: node_js
sudo: false

cache:
  directories:
    - $HOME/.npm

env:
  matrix:
  - NODE_VER=6 FULL_VALIDATE=false
  - NODE_VER=7 FULL_VALIDATE=false
  - NODE_VER=8 FULL_VALIDATE=true

matrix:
  fast_finish: true

before_install:
  - nvm install $NODE_VER
  - node -v && npm -v

install:
  - npm install
  - if [ "$FULL_VALIDATE" == "true" ]; then npm run lint; fi

script:
  - npm run build
  - npm test

after_success:
  - if [ "$FULL_VALIDATE" == "true" ]; then bash <(curl -s https://codecov.io/bash); fi